package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
)

func loadWords(objPath string) ([]string, error) {
	cmd := exec.Command("otool", "-t", objPath)
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("otool -t %s failed: %s", objPath, strings.TrimSpace(string(ee.Stderr)))
		}
		return nil, err
	}

	scanner := bufio.NewScanner(bytes.NewReader(out))
	words := make([]string, 0, 2048)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "(__TEXT") {
			continue
		}
		if strings.HasSuffix(line, ":") {
			continue
		}
		if strings.HasPrefix(line, objPath) {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		for _, word := range fields[1:] {
			if len(word) != 8 {
				continue
			}
			if !isHex(word) {
				continue
			}
			words = append(words, word)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(words) == 0 {
		return nil, fmt.Errorf("no words found in %s", objPath)
	}
	return words, nil
}

func isHex(s string) bool {
	for i := 0; i < len(s); i++ {
		switch c := s[i]; {
		case '0' <= c && c <= '9':
			continue
		case 'a' <= c && c <= 'f':
			continue
		case 'A' <= c && c <= 'F':
			continue
		default:
			return false
		}
	}
	return true
}

func emitWords(words []string, out io.Writer) {
	for _, word := range words {
		fmt.Fprintf(out, "\tWORD $0x%s\n", word)
	}
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gen_imdct_postrotate.go <obj.o> <out.s>")
		os.Exit(2)
	}
	objPath := os.Args[1]
	outPath := os.Args[2]

	words, err := loadWords(objPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	out, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by gen_imdct_postrotate.go; DO NOT EDIT.")
	fmt.Fprintln(out, "//go:build arm64 && !purego\n")
	fmt.Fprintln(out, "#include \"textflag.h\"\n")

	fmt.Fprintln(out, "TEXT \u00b7imdctPostRotateF32(SB), NOSPLIT, $0-64")
	fmt.Fprintln(out, "\tMOVD\tbuf_base+0(FP), R0")
	fmt.Fprintln(out, "\tMOVD\ttrig_base+24(FP), R1")
	fmt.Fprintln(out, "\tMOVD\tn2+48(FP), R2")
	fmt.Fprintln(out, "\tMOVD\tn4+56(FP), R3")
	emitWords(words, out)
	fmt.Fprintln(out)
}
