package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
)

func loadWords(objPath string) ([]string, error) {
	cmd := exec.Command("otool", "-t", objPath)
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("otool -t %s failed: %s", objPath, strings.TrimSpace(string(ee.Stderr)))
		}
		return nil, err
	}

	scanner := bufio.NewScanner(bytes.NewReader(out))
	words := make([]string, 0, 1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "(__TEXT") {
			continue
		}
		if strings.HasSuffix(line, ":") {
			continue
		}
		if strings.HasPrefix(line, objPath) {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		for _, word := range fields[1:] {
			if len(word) != 8 {
				continue
			}
			if !isHex(word) {
				continue
			}
			words = append(words, word)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(words) == 0 {
		return nil, fmt.Errorf("no words found in %s", objPath)
	}
	return words, nil
}

func isHex(s string) bool {
	for i := 0; i < len(s); i++ {
		switch c := s[i]; {
		case '0' <= c && c <= '9':
			continue
		case 'a' <= c && c <= 'f':
			continue
		case 'A' <= c && c <= 'F':
			continue
		default:
			return false
		}
	}
	return true
}

func emitWords(words []string, out io.Writer) {
	for _, word := range words {
		fmt.Fprintf(out, "\tWORD $0x%s\n", word)
	}
}

func main() {
	if len(os.Args) != 4 {
		fmt.Fprintln(os.Stderr, "usage: gen_kf_bfly35.go <bfly3.o> <bfly5.o> <out.s>")
		os.Exit(2)
	}
	bfly3Obj := os.Args[1]
	bfly5Obj := os.Args[2]
	outPath := os.Args[3]

	bfly3Words, err := loadWords(bfly3Obj)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	bfly5Words, err := loadWords(bfly5Obj)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	out, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by gen_kf_bfly35.go; DO NOT EDIT.")
	fmt.Fprintln(out, "//go:build arm64 && !purego\n")
	fmt.Fprintln(out, "#include \"textflag.h\"\n")

	fmt.Fprintln(out, "TEXT \u00b7kfBfly3M1(SB), NOSPLIT, $0-72")
	fmt.Fprintln(out, "\tMOVD\tfout_base+0(FP), R0")
	fmt.Fprintln(out, "\tMOVD\ttw_base+24(FP), R1")
	fmt.Fprintln(out, "\tMOVD\tfstride+48(FP), R2")
	fmt.Fprintln(out, "\tMOVD\tn+56(FP), R3")
	fmt.Fprintln(out, "\tMOVD\tmm+64(FP), R4")
	emitWords(bfly3Words, out)
	fmt.Fprintln(out)

	fmt.Fprintln(out, "TEXT \u00b7kfBfly5M1(SB), NOSPLIT, $0-72")
	fmt.Fprintln(out, "\tMOVD\tfout_base+0(FP), R0")
	fmt.Fprintln(out, "\tMOVD\ttw_base+24(FP), R1")
	fmt.Fprintln(out, "\tMOVD\tfstride+48(FP), R2")
	fmt.Fprintln(out, "\tMOVD\tn+56(FP), R3")
	fmt.Fprintln(out, "\tMOVD\tmm+64(FP), R4")
	emitWords(bfly5Words, out)
	fmt.Fprintln(out)
}
