package testvectors

// realcontent_corpus_quality_parity_test.go — REAL-CONTENT corpus parity gate.
//
// This is the broader real-content corpus (speech/music/noise) gate. The
// pre-existing corpus gates (corpus_signal_quality_parity_test.go,
// corpus_decoder_parity_test.go) exercise SYNTHETIC signal classes generated by
// internal/testsignal. This gate instead drives gopus with REAL recordings —
// speech and music clips extracted from the official RFC 6716/8251 Opus
// test-vector decoded reference outputs (see realcontent_corpus_fixture_test.go).
//
// For each real-content clip, each channel layout (mono downmix + stereo) and each
// codec mode (SILK / Hybrid / CELT, plus the bitrate extremes) the gate:
//
//   1. encodes the real-content PCM live with the gopus encoder,
//   2. decodes the SAME packets with BOTH gopus and the libopus reference whose
//      SIMD tier matches the gopus build (decodeWithMatchedTierReferencePacketsSingle:
//      asm gopus ↔ SIMD libopus, pure-Go gopus ↔ scalar libopus), and
//   3. gates gopus vs libopus with qualitycompare.AssertParity at the anchored
//      IntentNearExact bar.
//
// Both decoders consume identical packets, so the streams are sample-aligned and
// the near-exact bar measures gopus-vs-libopus decode parity on real material.
// The reference is always libopus (never gopus's own output): non-circular. No new
// thresholds, no magic numbers — the bar selection is entirely AssertParity's.

import (
	"testing"

	"github.com/thesyncim/gopus/internal/libopustest"
	"github.com/thesyncim/gopus/internal/qualitycompare"
)

// TestRealContentCorpusQualityParity gates gopus-vs-libopus decode parity on real
// speech/music clips encoded live with gopus and decoded by both gopus and the
// tier-matched libopus reference.
func TestRealContentCorpusQualityParity(t *testing.T) {
	t.Parallel()
	requireTestTier(t, testTierParity)
	libopustest.RequireOracle(t)

	const sampleRate = 48000
	const frameSize = 960 // 20 ms @ 48 kHz

	fixture, err := loadRealcontentFixture()
	if err != nil {
		t.Skipf("real-content corpus fixture unavailable (generate with tools/gen_realcontent_corpus_fixture.go): %v", err)
	}
	if fixture.Version != 1 {
		t.Fatalf("unsupported real-content fixture version: %d", fixture.Version)
	}
	if len(fixture.Cases) == 0 {
		t.Fatal("real-content fixture has no cases")
	}

	for _, c := range fixture.Cases {
		c := c
		for _, channels := range []int{1, 2} {
			channels := channels
			for _, cfg := range corpusQualityModeConfigs {
				cfg := cfg
				name := c.ContentKind + "/" + c.Name + "/" + chanName(channels) + "/" + cfg.name
				t.Run(name, func(t *testing.T) {
					t.Parallel()

					pcm := c.stereo
					if channels == 1 {
						pcm = realcontentMono(c.stereo)
					}
					if len(pcm) == 0 {
						t.Fatalf("empty source PCM for %s", name)
					}

					packets := encodeCorpusQualityPackets(t, pcm, channels, frameSize, cfg)

					gopusDecoded := decodeWithInternalDecoder(t, packets, channels)
					if len(gopusDecoded) == 0 {
						t.Fatal("gopus decoded empty output")
					}

					refDecoded, err := decodeWithMatchedTierReferencePacketsSingle(channels, frameSize, packets)
					if err != nil {
						libopustest.HelperUnavailable(t, "matched-tier reference decode", err)
					}
					if len(refDecoded) == 0 {
						t.Fatal("libopus reference decoded empty output")
					}

					n := len(gopusDecoded)
					if len(refDecoded) < n {
						n = len(refDecoded)
					}
					profile := qualitycompare.CodedProfile(sampleRate, channels, n)
					qualitycompare.AssertParity(t, gopusDecoded[:n], refDecoded[:n], profile,
						qualitycompare.IntentNearExact, name)
				})
			}
		}
	}
}

// TestRealContentDecodeOfLibopusPacketsParity gates the decode-of-libopus-packets
// lane on real content: it decodes the frozen libopus opus_demo encodes of each
// real clip with BOTH gopus and the tier-matched libopus reference, then gates
// gopus vs libopus with AssertParity at IntentNearExact. The packets are real
// libopus output (the fixture freezes only the bitstream), and the decode
// reference is produced live and tier-matched at gate time, so the reference is
// always libopus — never gopus's own output.
func TestRealContentDecodeOfLibopusPacketsParity(t *testing.T) {
	t.Parallel()
	requireTestTier(t, testTierParity)
	libopustest.RequireOracle(t)

	const sampleRate = 48000

	fixture, err := loadRealcontentFixture()
	if err != nil {
		t.Skipf("real-content corpus fixture unavailable: %v", err)
	}

	sawPackets := false
	for _, c := range fixture.Cases {
		c := c
		for _, enc := range c.LibopusPackets {
			enc := enc
			if len(enc.decodedPackets) == 0 {
				continue
			}
			sawPackets = true
			name := c.ContentKind + "/" + c.Name + "/" + chanName(enc.Channels) + "/libopus-" + enc.Name
			t.Run(name, func(t *testing.T) {
				t.Parallel()

				gopusDecoded := decodeWithInternalDecoder(t, enc.decodedPackets, enc.Channels)
				if len(gopusDecoded) == 0 {
					t.Fatal("gopus decoded empty output")
				}

				refDecoded, err := decodeWithMatchedTierReferencePacketsSingle(enc.Channels, enc.FrameSize, enc.decodedPackets)
				if err != nil {
					libopustest.HelperUnavailable(t, "matched-tier reference decode", err)
				}
				if len(refDecoded) == 0 {
					t.Fatal("libopus reference decoded empty output")
				}

				n := len(gopusDecoded)
				if len(refDecoded) < n {
					n = len(refDecoded)
				}
				profile := qualitycompare.CodedProfile(sampleRate, enc.Channels, n)
				qualitycompare.AssertParity(t, gopusDecoded[:n], refDecoded[:n], profile,
					qualitycompare.IntentNearExact, name)
			})
		}
	}
	if !sawPackets {
		t.Skip("real-content fixture carries no libopus packets (regenerate with opus_demo available)")
	}
}

// TestRealContentCorpusCoverage asserts the real-content fixture covers the three
// primary real-world content kinds (speech, music, mixed) so the corpus is not
// silently narrowed by a regenerate. Distinct from TestCorpusSignalClassCoverage,
// which guards the SYNTHETIC signal-class fixture.
func TestRealContentCorpusCoverage(t *testing.T) {
	t.Parallel()
	requireTestTier(t, testTierFast)

	fixture, err := loadRealcontentFixture()
	if err != nil {
		t.Skipf("real-content corpus fixture unavailable (generate with tools/gen_realcontent_corpus_fixture.go): %v", err)
	}

	seen := make(map[string]int)
	libopusModes := map[string]int{"silk": 0, "hybrid": 0, "celt": 0}
	for _, c := range fixture.Cases {
		seen[c.ContentKind]++
		if c.SourceFile == "" {
			t.Errorf("case %s missing source_file provenance", c.Name)
		}
		if c.PCMSHA256 == "" {
			t.Errorf("case %s missing pcm_sha256", c.Name)
		}
		if len(c.stereo) == 0 {
			t.Errorf("case %s decoded to empty PCM", c.Name)
		}
		for _, enc := range c.LibopusPackets {
			for mode, count := range enc.ModeHistogram {
				if count > 0 {
					libopusModes[mode] += count
				}
			}
		}
	}

	for _, kind := range []string{"speech", "music", "mixed"} {
		if seen[kind] == 0 {
			t.Errorf("real-content fixture missing content kind: %s", kind)
		}
	}

	// If the fixture carries libopus packets at all, they must cover all three
	// codec modes so the decode-of-libopus-packets lane is not silently narrowed.
	if libopusModes["silk"]+libopusModes["hybrid"]+libopusModes["celt"] > 0 {
		for _, mode := range []string{"silk", "hybrid", "celt"} {
			if libopusModes[mode] == 0 {
				t.Errorf("real-content libopus packets missing codec mode: %s", mode)
			}
		}
	}

	if fixture.Source.Origin == "" {
		t.Error("real-content fixture missing source.origin provenance")
	}

	t.Logf("real-content cases: %d (speech=%d music=%d mixed=%d)",
		len(fixture.Cases), seen["speech"], seen["music"], seen["mixed"])
	t.Logf("libopus packet modes: silk=%d hybrid=%d celt=%d", libopusModes["silk"], libopusModes["hybrid"], libopusModes["celt"])
	t.Logf("source: %s", fixture.Source.Origin)
}

// TestRealContentCorpusFixtureIntegrity verifies each committed clip still matches
// its recorded sha256 — i.e. the real-content source PCM has not drifted from what
// the generator produced from the RFC vectors.
func TestRealContentCorpusFixtureIntegrity(t *testing.T) {
	t.Parallel()
	requireTestTier(t, testTierFast)

	fixture, err := loadRealcontentFixture()
	if err != nil {
		t.Skipf("real-content corpus fixture unavailable: %v", err)
	}
	for _, c := range fixture.Cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			t.Parallel()
			got := realcontentClipSHA256(c.stereo)
			if got != c.PCMSHA256 {
				t.Fatalf("clip %s sha256 mismatch: fixture=%s recomputed=%s", c.Name, c.PCMSHA256, got)
			}
		})
	}
}
