//go:build ignore

package main

import (
	"bufio"
	"flag"
	"fmt"
	"math"
	"os"
	"strconv"
	"strings"
	"unicode"
)

type fftTwiddle struct{ real, imag float32 }

func pinnedQEXTFFTTwiddles() ([]fftTwiddle, error) {
	paths := []string{
		"tmp_check/opus-1.6.1/celt/static_modes_float.h",
		"../../tmp_check/opus-1.6.1/celt/static_modes_float.h",
	}
	var source []byte
	var err error
	for _, path := range paths {
		source, err = os.ReadFile(path)
		if err == nil {
			break
		}
	}
	if err != nil {
		return nil, fmt.Errorf("read pinned libopus static modes: %w", err)
	}
	const declaration = "static const kiss_twiddle_cpx fft_twiddles96000_1920[960] = {"
	start := strings.Index(string(source), declaration)
	if start < 0 {
		return nil, fmt.Errorf("pinned libopus fft_twiddles96000_1920 declaration missing")
	}
	body := string(source[start+len(declaration):])
	end := strings.Index(body, "};")
	if end < 0 {
		return nil, fmt.Errorf("pinned libopus fft_twiddles96000_1920 terminator missing")
	}
	fields := strings.FieldsFunc(body[:end], func(r rune) bool {
		return r == '{' || r == '}' || r == ',' || unicode.IsSpace(r)
	})
	if len(fields) != 960*2 {
		return nil, fmt.Errorf("pinned libopus FFT table has %d components, want 1920", len(fields))
	}
	twiddles := make([]fftTwiddle, 960)
	for i := range twiddles {
		realPart, err := strconv.ParseFloat(strings.TrimSuffix(fields[2*i], "f"), 32)
		if err != nil {
			return nil, fmt.Errorf("pinned libopus FFT twiddle[%d].real: %w", i, err)
		}
		imagPart, err := strconv.ParseFloat(strings.TrimSuffix(fields[2*i+1], "f"), 32)
		if err != nil {
			return nil, fmt.Errorf("pinned libopus FFT twiddle[%d].imag: %w", i, err)
		}
		twiddles[i] = fftTwiddle{float32(realPart), float32(imagPart)}
	}
	return twiddles, nil
}

func main() {
	out := flag.String("out", "internal/celt/kissfft960_static_qext.go", "output file path")
	flag.Parse()
	twiddles, err := pinnedQEXTFFTTwiddles()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	file, err := os.Create(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer file.Close()
	w := bufio.NewWriter(file)
	fmt.Fprintln(w, "// Code generated by tools/gen_qext_fft_twiddles.go; DO NOT EDIT.")
	fmt.Fprintln(w, "//go:build gopus_qext")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package celt")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "import \"math\"")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// fftTwiddles960QEXTStatic mirrors pinned libopus")
	fmt.Fprintln(w, "// celt/static_modes_float.h fft_twiddles96000_1920.")
	fmt.Fprintln(w, "var fftTwiddles960QEXTStatic = [960]kissCpx{")
	for _, twiddle := range twiddles {
		fmt.Fprintf(w, "\t{r: math.Float32frombits(0x%08x), i: math.Float32frombits(0x%08x)},\n",
			math.Float32bits(twiddle.real), math.Float32bits(twiddle.imag))
	}
	fmt.Fprintln(w, "}")
	if err := w.Flush(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
