//go:build ignore

package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func pinnedQEXTTrig() ([]float32, error) {
	paths := []string{
		"tmp_check/opus-1.6.1/celt/static_modes_float.h",
		"../../tmp_check/opus-1.6.1/celt/static_modes_float.h",
	}
	var source []byte
	var err error
	for _, path := range paths {
		source, err = os.ReadFile(path)
		if err == nil {
			break
		}
	}
	if err != nil {
		return nil, fmt.Errorf("read pinned libopus static modes: %w", err)
	}
	const declaration = "static const celt_coef mdct_twiddles1920[3600] = {"
	start := strings.Index(string(source), declaration)
	if start < 0 {
		return nil, fmt.Errorf("pinned libopus mdct_twiddles1920 declaration missing")
	}
	body := string(source[start+len(declaration):])
	end := strings.Index(body, "};")
	if end < 0 {
		return nil, fmt.Errorf("pinned libopus mdct_twiddles1920 terminator missing")
	}
	fields := strings.Fields(strings.ReplaceAll(body[:end], ",", " "))
	if len(fields) != 3600 {
		return nil, fmt.Errorf("pinned libopus mdct_twiddles1920 has %d values, want 3600", len(fields))
	}
	// The N=3840 long MDCT uses the first N/2 coefficients. Its shorter
	// shift segments match the existing N=1920/960/480 static CELT tables.
	trig := make([]float32, 1920)
	for i := range trig {
		value, err := strconv.ParseFloat(strings.TrimSuffix(fields[i], "f"), 32)
		if err != nil {
			return nil, fmt.Errorf("pinned libopus mdct_twiddles1920[%d]: %w", i, err)
		}
		trig[i] = float32(value)
	}
	return trig, nil
}

func main() {
	out := flag.String("out", "internal/celt/mdct_trig_static_3840_qext.go", "output file path")
	flag.Parse()
	trig, err := pinnedQEXTTrig()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	file, err := os.Create(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer file.Close()
	w := bufio.NewWriter(file)
	fmt.Fprintln(w, "// Code generated by tools/gen_qext_mdct_trig.go; DO NOT EDIT.")
	fmt.Fprintln(w, "//go:build gopus_qext")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package celt")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// mdctTrig3840F32Static mirrors pinned libopus celt/static_modes_float.h")
	fmt.Fprintln(w, "// mdct_twiddles1920[0:1920] for the native 96 kHz long inverse MDCT.")
	fmt.Fprintln(w, "var mdctTrig3840F32Static = [1920]float32{")
	for i, value := range trig {
		if i%5 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%s,", strconv.FormatFloat(float64(value), 'g', 9, 32))
		if i%5 == 4 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "func getMDCTTrig3840F32() []float32 { return mdctTrig3840F32Static[:] }")
	if err := w.Flush(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
