//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"flag"
	"fmt"
	"math"
	"os"
	"strconv"
)

var window120StaticF32 = [120]float32{
	6.7286966e-05, 0.00060551348, 0.0016815970, 0.0032947962, 0.0054439943,
	0.0081276923, 0.011344001, 0.015090633, 0.019364886, 0.024163635,
	0.029483315, 0.035319905, 0.041668911, 0.048525347, 0.055883718,
	0.063737999, 0.072081616, 0.080907428, 0.090207705, 0.099974111,
	0.11019769, 0.12086883, 0.13197729, 0.14351214, 0.15546177,
	0.16781389, 0.18055550, 0.19367290, 0.20715171, 0.22097682,
	0.23513243, 0.24960208, 0.26436860, 0.27941419, 0.29472040,
	0.31026818, 0.32603788, 0.34200931, 0.35816177, 0.37447407,
	0.39092462, 0.40749142, 0.42415215, 0.44088423, 0.45766484,
	0.47447104, 0.49127978, 0.50806798, 0.52481261, 0.54149077,
	0.55807973, 0.57455701, 0.59090049, 0.60708841, 0.62309951,
	0.63891306, 0.65450896, 0.66986776, 0.68497077, 0.69980010,
	0.71433873, 0.72857055, 0.74248043, 0.75605425, 0.76927895,
	0.78214257, 0.79463430, 0.80674445, 0.81846456, 0.82978733,
	0.84070669, 0.85121779, 0.86131698, 0.87100183, 0.88027111,
	0.88912479, 0.89756398, 0.90559094, 0.91320904, 0.92042270,
	0.92723738, 0.93365955, 0.93969656, 0.94535671, 0.95064907,
	0.95558353, 0.96017067, 0.96442171, 0.96834849, 0.97196334,
	0.97527906, 0.97830883, 0.98106616, 0.98356480, 0.98581869,
	0.98784191, 0.98964856, 0.99125274, 0.99266849, 0.99390969,
	0.99499004, 0.99592297, 0.99672162, 0.99739874, 0.99796667,
	0.99843728, 0.99882195, 0.99913147, 0.99937606, 0.99956527,
	0.99970802, 0.99981248, 0.99988613, 0.99993565, 0.99996697,
	0.99998518, 0.99999457, 0.99999859, 0.99999982, 1.0000000,
}

func vorbisWindow(i, overlap int) float64 {
	x := float64(i) + 0.5
	sinArg := 0.5 * math.Pi * x / float64(overlap)
	s := math.Sin(sinArg)
	return math.Sin(0.5 * math.Pi * s * s)
}

func emitFloat64Array(w *bufio.Writer, name, typeExpr string, vals []float64) {
	fmt.Fprintf(w, "var %s = %s{\n", name, typeExpr)
	for i, v := range vals {
		if i%5 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%s,", strconv.FormatFloat(v, 'g', 17, 64))
		if i%5 == 4 || i == len(vals)-1 {
			fmt.Fprint(w, "\n")
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprint(w, "}\n\n")
}

func emitFloat32Array(w *bufio.Writer, name, typeExpr string, vals []float32) {
	fmt.Fprintf(w, "var %s = %s{\n", name, typeExpr)
	for i, v := range vals {
		if i%5 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%s,", strconv.FormatFloat(float64(v), 'g', 9, 32))
		if i%5 == 4 || i == len(vals)-1 {
			fmt.Fprint(w, "\n")
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprint(w, "}\n\n")
}

func main() {
	out := flag.String("out", "celt/window_tables_static.go", "output file path")
	flag.Parse()

	overlaps := []int{120, 240, 480, 960}
	f64ByOverlap := map[int][]float64{}
	f32ByOverlap := map[int][]float32{}
	sqByOverlap := map[int][]float64{}

	for _, overlap := range overlaps {
		f64 := make([]float64, overlap)
		f32 := make([]float32, overlap)
		sq := make([]float64, overlap)
		if overlap == 120 {
			for i := 0; i < overlap; i++ {
				f32[i] = window120StaticF32[i]
				f64[i] = float64(f32[i])
				sq[i] = f64[i] * f64[i]
			}
		} else {
			for i := 0; i < overlap; i++ {
				f64[i] = vorbisWindow(i, overlap)
				f32[i] = float32(f64[i])
				sq[i] = f64[i] * f64[i]
			}
		}
		f64ByOverlap[overlap] = f64
		f32ByOverlap[overlap] = f32
		sqByOverlap[overlap] = sq
	}

	f, err := os.Create(*out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to create %s: %v\n", *out, err)
		os.Exit(1)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	defer w.Flush()

	fmt.Fprintln(w, "// Code generated by tools/gen_window_tables.go; DO NOT EDIT.")
	fmt.Fprintln(w, "package celt")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// windowBuffer120 contains precomputed Vorbis window values for overlap=Overlap.")
	emitFloat64Array(w, "windowBuffer120", "[Overlap]float64", f64ByOverlap[120])
	emitFloat32Array(w, "windowBuffer120F32", "[Overlap]float32", f32ByOverlap[120])
	emitFloat64Array(w, "windowBuffer120Sq", "[Overlap]float64", sqByOverlap[120])

	fmt.Fprintln(w, "// windowBuffer240 contains precomputed window for 5ms frames.")
	emitFloat64Array(w, "windowBuffer240", "[240]float64", f64ByOverlap[240])
	emitFloat32Array(w, "windowBuffer240F32", "[240]float32", f32ByOverlap[240])
	emitFloat64Array(w, "windowBuffer240Sq", "[240]float64", sqByOverlap[240])

	fmt.Fprintln(w, "// windowBuffer480 contains precomputed window for 10ms frames.")
	emitFloat64Array(w, "windowBuffer480", "[480]float64", f64ByOverlap[480])
	emitFloat32Array(w, "windowBuffer480F32", "[480]float32", f32ByOverlap[480])
	emitFloat64Array(w, "windowBuffer480Sq", "[480]float64", sqByOverlap[480])

	fmt.Fprintln(w, "// windowBuffer960 contains precomputed window for 20ms frames.")
	emitFloat64Array(w, "windowBuffer960", "[960]float64", f64ByOverlap[960])
	emitFloat32Array(w, "windowBuffer960F32", "[960]float32", f32ByOverlap[960])
	emitFloat64Array(w, "windowBuffer960Sq", "[960]float64", sqByOverlap[960])
}
