#!/usr/bin/env bash
set -euo pipefail

GO_BIN="${GO:-go}"
GO_WORK_ENV="${GO_WORK_ENV:-GOWORK=off}"
go_env=()
if [[ -n "$GO_WORK_ENV" ]]; then
	# Makefile passes GO_WORK_ENV as simple KEY=VALUE assignments.
	# shellcheck disable=SC2206
	go_env=($GO_WORK_ENV)
fi

json_out="$(mktemp)"
json_part="$json_out.part"
trap 'rm -f "$json_out" "$json_part"' EXIT

run_json() {
	if ! "$@" >"$json_part"; then
		cat "$json_part"
		cat "$json_part" >>"$json_out"
		exit 1
	fi
	if ! grep -q '"Action":"run"' "$json_part"; then
		cat "$json_part"
		echo "Focused gate command matched no tests: $*"
		cat "$json_part" >>"$json_out"
		exit 1
	fi
	cat "$json_part"
	cat "$json_part" >>"$json_out"
	: >"$json_part"
}

run_go_test_json() {
	local -a cmd_env=()
	while (($#)) && [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do
		cmd_env+=("$1")
		shift
	done
	local -a env_args=()
	if ((${#cmd_env[@]})); then
		env_args+=("${cmd_env[@]}")
	fi
	if ((${#go_env[@]})); then
		env_args+=("${go_env[@]}")
	fi
	run_json env "${env_args[@]}" "$GO_BIN" test -json -count=1 "$@"
}

run_parity() {
	run_go_test_json GOPUS_TEST_TIER=parity GOPUS_STRICT_LIBOPUS_REF=1 "$@"
}

run_exactness() {
	run_go_test_json GOPUS_TEST_TIER=fast GOPUS_LIBOPUS_EXACTNESS=1 "$@"
}

run_exhaustive() {
	run_go_test_json GOPUS_TEST_TIER=exhaustive "$@"
}

run_tagged_parity() {
	local tags="$1"
	shift
	run_parity -tags "$tags" "$@"
}

require_no_skips() {
	local label="$1"
	if grep -q '"Action":"skip"' "$json_out"; then
		echo "Unexpected skip detected in required $label gate:"
		grep '"Action":"skip"' "$json_out"
		exit 1
	fi
}

join_pipe() {
	local IFS='|'
	printf '%s' "$*"
}

test_regex() {
	printf 'Test(%s)' "$(join_pipe "$@")"
}

tag_dred='gopus_dred'
tag_qext='gopus_qext'
tag_extra_controls='gopus_extra_controls'
tag_dred_qext='gopus_dred gopus_qext'
tag_extra_controls_qext='gopus_extra_controls gopus_qext'
tag_all_optional='gopus_dred gopus_extra_controls gopus_qext'

# Default-build DNN-blob surface: SetDNNBlob is now a tag-gated, zero-cost
# no-op (mirroring libopus USE_WEIGHTS_FILE compile-gating), so the default
# gate asserts the no-op contract and dormancy; model-loading retention tests
# run under the gopus_dred/gopus_extra_controls tags (dnn_blob_tagged_root).
dnn_blob_default_root='Test(DefaultBuildSetDNNBlobIsNoOp|DefaultBuildDNNBlobKeepsDREDRuntimeDormant|DefaultBuildEncoderDNNBlobKeepsDREDDormant|ValidEncoderTestDNNBlobShape|ValidDecoderTestDNNBlobShape)'
dnn_blob_tagged_root='Test(DNNBlobControlAcceptsLibopusModelBlobs|HotPathAllocsDecodePLCDNNReadyAtMostBaseline|EncoderSetDNNBlobRetainedAcrossReset|DecoderSetDNNBlobRetainedAcrossReset|DecoderSetDNNBlobStereoRuntimeRetainedAcrossReset|MultistreamEncoderSetDNNBlobRetainedAcrossReset|MultistreamDecoderSetDNNBlobRetainedAcrossReset)'
dnn_blob_default_multistream='Test(DefaultBuildMultistreamDecoderRealBlobDormant|DefaultBuildMultistreamDecoderDecodeAllocGuard|DefaultBuildMultistreamEncoderDNNBlobKeepsAllocsFlat)'
dred_reference_internal='Test(DREDConstantsMatchLibopusReference|DREDStatsTablesMatchLibopusReference|DREDRDOVAEModelBlobsMatchPinnedLibopusDigests)'
dred_reference_dnnblob='Test(DNNBlobConstantsMatchLibopusReference|DREDModelManifestsMatchLibopusReference)'
dred_reference_rdovae='Test(RDOVAELayerSpecsMatchLibopusReference)'
dred_rdovae_real_model='Test(RDOVAEEncoderMatchesLibopusOnRealModel|RDOVAEDecoderMatchesLibopusOnRealModel)'
dred_recovery_window_root='StandaloneDREDRecoveryWindow(MatchesLibopus|16kMatchesLibopus)'
extra_controls_core_root="Test(SupportsOptionalExtension|ExtraControlsBuildExposesTopLevelControls|ExtraControlsBuildPublicAPIContract|PublicDRED|DREDDecoderParseRequiresModel|DREDDecoderParseAndProcessRetainsMetadata|DREDDecoderParseClearsStateWhenPacketHasNoDRED|DREDDecoderParseClearsStateOnMalformedPacket|StandaloneDREDParseMatchesLibopus|StandaloneDREDProcessMatchesLibopusOnRealPacket|StandaloneDREDProcessMatchesLibopusOnQualityPacket|StandaloneDREDProcessLifecycleMatchesLibopusOnRealPacket|$dred_recovery_window_root|StandaloneDREDRecoveryQueueMatchesLibopus|DecoderCoreDNNBlobDoesNotArmGoodPacketDREDWork|DecoderCachedDREDRecoveryMatchesLibopusLifecycle|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kCELT|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kHybrid|DecoderCachedDREDRecoveryCursorTracksLosses16kCELT|DecoderCachedDREDRecoveryCursorTracksLosses16kHybrid|DecoderCachedDREDRecoveryCursorTracksLosses48kCELT|DecoderCachedDREDRecoveryCursorTracksLosses48kHybrid|DecoderExplicitDREDWarmup48kStateMatchesLibopus)|ExampleSupportsOptionalExtension"
dred_stereo_recovery_root='Test(DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kCELTStereo|DecoderCachedDREDRecoveryCursorTracksLosses16kCELTStereo|DecoderCachedDREDRecoveryCursorTracksLosses16kHybridStereo|DecoderCachedDREDRecoveryCursorTracksLosses48kCELTStereo|DecoderCachedDREDRecoveryCursorTracksLosses48kHybridStereo)'
dred_latents_trace='TestLibopusDREDLatentsTraceStereoDivergesFromMono'
dred_decoder_dormancy_root='Test(DecoderCoreDNNBlobDoesNotArmGoodPacketDREDWork|NewDecoderLeavesDREDPayloadBufferDormant|StandaloneDREDArmKeepsRecoveryNeuralAnd48kBridgeDormant|MainDecoderDNNBlobKeepsRecoveryAndPayloadDormant|MainDecoder48kDNNBlobKeepsRecoveryAndBridgeDormant|MainDecoder16kDNNBlobGoodDecodeKeepsRecoveryDormantUntilLoss|MainDecoder48kDNNBlobGoodDecodeKeepsRecoveryDormantUntilLoss|MainDecoder48kDNNBlobGoodSILKHybridDecodeKeepsRecoveryDormantUntilLoss|ClearingStandaloneDREDPreservesMainNeuralState|DecoderCachesDREDPayloadWhenDREDModelLoaded|DecoderCachesDREDSampleTimingForLaterFrame|DecoderLeavesDREDPayloadDormantWithoutDREDModel|DecoderLeavesDREDStateDormantWithoutAnySidecar|PublicDecoderSetDNNBlobDoesNotArmDREDDecoderWhenBlobContainsModel|DecoderLeavesDREDPayloadDormantWhenIgnoringExtensions|DecoderDREDCacheFollowsStandaloneModelAndIgnoreExtensions|DecoderResetDropsActivatedDREDRuntimeBackToDormant)'
dred_decoder_recovery_internal_root='Test(DecoderDREDRecoveryBlendFollowsLifecycle|DecoderMarkDREDUpdatedPCMRefreshesNeuralHistory|DecoderMarkDREDUpdatedPCMCELTKeepsBridgeOwnedHistory|DecoderMarkDREDUpdatedPCMDormantWithoutSidecar|DecoderMarkDREDUpdatedPCMDoesNotTrackHistoryWithoutNeuralConcealment|DecoderPrimeDREDCELTEntryHistoryUsesCELTBridge|DecoderPrimeDREDCELTEntryHistoryStaysDormantWithoutNeuralConcealment|DecoderDecodePLCAppliesNeuralConcealmentWhenReady)'
dred_encoder_runtime_internal='Test(EncoderDREDInitialLatentsTraceMatchesLibopus|EncoderDREDLongCELTLatentsUseLibopusSubframeCadence|EncoderProcessDREDLatentsDownmixesStereo16k|EncoderProcessDREDLatentsSupportsRateConversion|EncoderProcessDREDLatentsBuffers48k10msFrames|EncoderProcessDREDLatentsTracksHistoryWindow|EncoderProcessDREDLatentsTracksOffsets|EncoderBuildDREDExperimentalPayloadUsesRuntimeHistory|EncoderBuildDREDExperimentalPayloadDoesNotAllocate|EncoderSetDREDDurationGrowsScratchPacketWhenArmed)'
dred_encoder_payload_root='Test(EncoderCarriedDREDPayloadMatchesLibopusCELTFullband20msStereo|EncoderSilkMono20msPrimaryFrameByteExactMatchesLibopus|EncoderSilkMono40msPrimaryFrameByteExactMatchesLibopus|EncoderSilkMono60msPrimaryFrameByteExactMatchesLibopus|EncoderSilkStereo20msPrimaryFrameByteExactMatchesLibopus|EncoderCarriedDREDPayloadMatchesLibopusCELTFullband20ms|EncoderCarriedDREDPayloadMatchesLibopusCELTFullbandLongFrames|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msCBR|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband40ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband60ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWidebandLongFrames|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20ms|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40ms|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msStereo|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msStereoPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msStereo|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msStereo|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband40msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusCELTFullband20msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msStereo)'
dred_payload_parser_root='TestFindDREDPayload'
dred_multistream_dormancy='Test(NewDecoderLeavesDREDSidecarDormant|DecoderCachesDREDPayloadPerStreamWhenModelLoaded|DecoderCachesDREDSampleTimingForLaterStreamFrame|DecoderLeavesDREDPayloadDormantWithoutDREDModel|DecoderLeavesDREDStateDormantWithoutAnySidecar|DecoderLeavesDREDStateDormantWithOnlyMainDNNBlob|DecoderLeavesDREDPayloadDormantWhenIgnoringExtensions|DecoderDREDCacheFollowsStandaloneModelAndIgnoreExtensions|DecoderDoesNotCachePartialDREDStateWhenLaterStreamFails|DREDBuildTagExposesEncoderControlsOnlyReadyRequiresEveryStream)'
extra_controls_multistream_dormancy='Test(NewDecoderLeavesDREDSidecarDormant|DecoderCachesDREDPayloadPerStreamWhenModelLoaded|DecoderCachesDREDSampleTimingForLaterStreamFrame|DecoderLeavesDREDPayloadDormantWithoutDREDModel|DecoderLeavesDREDStateDormantWithoutAnySidecar|DecoderLeavesDREDStateDormantWithOnlyMainDNNBlob|DecoderLeavesDREDPayloadDormantWhenIgnoringExtensions|DecoderDREDCacheFollowsStandaloneModelAndIgnoreExtensions|DecoderDoesNotCachePartialDREDStateWhenLaterStreamFails|EncoderDREDReadyRequiresModelAndDurationOnEveryStream)'
dred_multistream_recovery_internal='TestDecoderDREDRecoveryBlendFollowsLifecycle'
dred_multistream_neural_decode_cases=(
	DecoderDecodeNilConsumesMultistreamDREDNeuralStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralHybridMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralSILKMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralCELTNonFinalMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralHybridNonFinalMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralSILKNonFinalMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondMonoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralCELTStereoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalStereoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralCELTSecondCoupledStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondCoupledStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralHybridStereoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalStereoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralHybridSecondCoupledStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondCoupledStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralSILKStereoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalStereoStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralSILKSecondCoupledStream
	DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondCoupledStream
)
dred_multistream_neural_decodes="$(join_pipe "${dred_multistream_neural_decode_cases[@]}")"
qext_packet_extension_root='Test(GeneratePacketExtensionsMatchesLibopusCases|PacketExtensionIteratorParseAndCount|PacketExtensionIteratorRepeatExpansion|PacketExtensionIteratorRejectsInvalidSeparator|MultistreamPacketPadUnpadSelfDelimitedRoundTrip|MultistreamPacketPadUnpadThreeStreamsRoundTrip|RepacketizerPreservesPacketExtensions|PacketPadPreservesPacketExtensions|SelfDelimitedPacketPreservesPacketExtensions|DecodeSelfDelimitedPacketPreservesOpaqueMalformedPadding)'
qext_packet_extension_multistream='Test(SelfDelimitedPacketPreservesPacketExtensions|DecodeSelfDelimitedPacketPreservesOpaqueMalformedPadding)'
qext_libopus_tooling='TestFindQEXTLibopusToolForOSUsesSeparateSourceTree'
doc_contract_root='Test(OptionalExtensionDocsContract|TrustDocsContract|ReleaseNotesSourceIsReadme|DefaultBuildIsZeroCostForGatedFeatures)'
doc_contract_testvectors='Test(FixtureGeneratorScriptsBuildIgnore|GeneratedFilesDeclareGeneratedMarkerBeforePackage|ParityMatrixFreshness)'
core_oracles_root='Test(Float32ToInt16MatchesLibopusFLOAT2INT16|OpusPCMSoftClipMatchesLibopus|SoftClipAndFloat32ToInt16MatchesLibopus|PacketDurationAtRateMatchesLibopus)'
core_oracles_celt='TestCELT(Log2|Exp2)MatchesLibopusFloatApprox|TestCELTAngleMathMatchesLibopusFloatPath|TestCELTStereoIthetaQ30MatchesLibopus|TestCELTBitexact(Cos|Log2Tan)MatchesLibopus|TestCELTBitexactLog2TanThetaTableMatchesLibopus|TestCELTIntegerMathMatchesLibopus'
core_oracles_dnnmath='TestCeltMathMatchesLibopusCELTOracle'
core_oracles_encoder='TestHybridCELTExp2ApproxMatchesLibopus'
core_oracles_lpcnetplc='TestLPCNetLog10fUsesLibopusCELTLog2Oracle'
core_oracles_multistream='TestAmbisonicsIsqrt32MatchesLibopusCELTOracle'
core_oracles_opusmath='TestCELT(Log2|Exp2|ISqrt32)MatchesLibopusOracle'
core_oracles_silk='TestSILK(Lin2Log|Log2Lin|Fixed|NLSF|A2|NLSF2A|Gains|Stereo|LTP|QuantLTPGains|Isqrt32|.*Resampler)'
core_oracles_range='TestRangeCoderMatchesLibopusOracle'
quality_testvectors='TestFinalRangeVerification|TestQualityFloat32ToPCM16UsesOpusRounding|TestEncoderComplianceSummary|TestEncoderCompliancePrecisionGuard|TestEncoderVariantProfileParityAgainstLibopusFixture|TestEncoderVariantCELTAllocationParityAgainstFixture|TestEncoderVariantCELTHeaderParityAgainstFixture|TestDecoderParityLibopusMatrix|TestDecoderLossParityLibopusFixture|TestDecoderHybridToCELT10msTransitionParity|TestDecoderHybridToCELT20msTransitionParity'
exactness_encoder='TestModeFixtureParityWithLibopus|TestAnalysisFixtureParityWithLibopus'
exhaustive_testvectors='TestEncoderCompliancePacketsFixtureHonestyWithOpusDemo|TestEncoderVariantsFixtureHonestyWithOpusDemo|TestDecoderParityMatrixFixtureHonestyWithOpusDemo|TestDecoderLossFixtureHonestyWithOpusDemo|TestLongFrameReferenceFixtureHonestyWithLiveOpusdec'
provenance_testvectors='TestEncoderVariantProfileProvenanceAudit'
extra_controls_parity_root='Test(ParsedDREDAvailabilityMatchesLibopus)'
extra_controls_parity_silk_dred_root='Test(DecoderExplicitSILKDREDDecodeMatchesLibopus|DecoderExplicit16kSILKDREDDecodeMatchesLibopus)'
extra_controls_parity_decoder_cases=(
	DecoderCachedDREDDecodeMatrixMatchesLiveSequenceOracle
	DecoderCachedStereoDREDDecodeMatchesLiveSequenceOracle
	DecoderCachedStereoDREDCELTMatrixMatchesLiveSequenceOracle
	DecoderCachedStereoDREDHybridMatrixMatchesLiveSequenceOracle
	DecoderCachedStereoDREDSecondLossMatchesLiveSequenceOracle
	DecoderCachedStereoDREDThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedStereoDREDSecondLossThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedDREDDecodeCELTSuperwidebandMatrixMatchesLiveSequenceOracle
	DecoderCachedDREDDecodeCELTWidebandMatrixMatchesLiveSequenceOracle
	DecoderCachedDREDThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedDREDThenNextPacketCELTSuperwidebandMatchesLiveSequenceOracle
	DecoderCachedDREDThenNextPacketCELTWidebandMatchesLiveSequenceOracle
	DecoderCachedDREDSecondLossMatchesLiveSequenceOracle
	DecoderCachedDREDSecondLossCELTSuperwidebandMatchesLiveSequenceOracle
	DecoderCachedDREDSecondLossCELTWidebandMatchesLiveSequenceOracle
	DecoderCachedDREDSecondLossThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedDREDSecondLossThenNextPacketCELTSuperwidebandMatchesLiveSequenceOracle
	DecoderCachedDREDSecondLossThenNextPacketCELTWidebandMatchesLiveSequenceOracle
	DecoderCachedHybridDREDDecodeMatrixMatchesLiveSequenceOracle
	DecoderCachedHybridDRED16kDecodeMatrixMatchesLiveSequenceOracle
	DecoderCachedHybridDREDAPIRateDecodeMatrixMatchesLiveSequenceOracle
	DecoderCachedHybridDREDThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedHybridDRED16kThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedHybridDREDAPIRateThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedHybridDREDSecondLossMatchesLiveSequenceOracle
	DecoderCachedHybridDRED16kSecondLossMatchesLiveSequenceOracle
	DecoderCachedHybridDREDAPIRateSecondLossMatchesLiveSequenceOracle
	DecoderCachedHybridSecondLossThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedHybridDRED16kSecondLossThenNextPacketMatchesLiveSequenceOracle
	DecoderCachedHybridDREDAPIRateSecondLossThenNextPacketMatchesLiveSequenceOracle
	DecoderSILKDecodeNilWithCachedDREDMatchesLiveLostOracle
	DecoderFirstLossNeuralConcealmentMatchesLiveSequenceOracle
	DecoderFirstLossNeuralConcealment16kFrameSizeMatrixMatchesLiveSequenceOracle
	DecoderFirstLossThenNextPacketMatchesLiveSequenceOracle
	DecoderFirstLossThenNextPacket16kFrameSizeMatrixMatchesLiveSequenceOracle
	DecoderSecondLossNeuralConcealmentMatchesLiveSequenceOracle
	DecoderSecondLossNeuralConcealment16kFrameSizeMatrixMatchesLiveSequenceOracle
	DecoderSecondLossThenNextPacketMatchesLiveSequenceOracle
	DecoderSecondLossThenNextPacket16kFrameSizeMatrixMatchesLiveSequenceOracle
	DecoderExplicitDREDCELT48kBridgeMatchesLibopusFirstLoss
	DecoderExplicitDREDCELT48kBridgeMatchesLibopusSecondLoss
	DecoderExplicitDREDDecodeMatchesLibopus
	DecoderExplicitStereoDREDDecodeMatchesLibopus
	DecoderExplicitStereoDRED16kDecodeMatchesLibopus
	DecoderExplicitStereoHybridDRED16kDecodeMatchesLibopus
	DecoderExplicitSILKDREDDecodeStereoMatchesLibopus
	DecoderExplicitDREDDecode16kMatchesLibopus
	DecoderExplicitDREDDecode16kCELTSuperwidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecode16kCELTWidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeSecondLossMatchesLibopus
	DecoderExplicitDREDDecodeSecondLossGainTransitionMatchesLibopus
	DecoderExplicitDREDDecodeSecondLoss16kMatchesLibopus
	DecoderExplicitDREDDecodeOffsetMatrixMatchesLibopus
	DecoderExplicitDREDDecodeOffsetMatrixCELTSuperwidebandMatchesLibopus
	DecoderExplicitDREDDecodeOffsetMatrixHybridSuperwidebandMatchesLibopus
	DecoderExplicitDREDDecodeOffsetMatrixHybridFullbandMatchesLibopus
	DecoderExplicitDREDDecodeOffsetMatrix16kHybridMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacketMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacket16kMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacket16kFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacket16kCELTSuperwidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacket16kCELTWidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecode16kMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeAPIRateMatrixMatchesLibopus
	DecoderExplicit16kHybridDREDDecodeMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeThenNextPacketMatchesLibopus
	DecoderExplicitHybridDREDDecodeThenNextPacket16kMatchesLibopus
	DecoderExplicitHybridDREDDecodeThenNextPacketAPIRateMatchesLibopus
	DecoderExplicitHybridDREDDecodeSecondLossMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeSecondLoss16kMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeSecondLossAPIRateMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeSecondLossThenNextPacketMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeSecondLossThenNextPacket16kMatrixMatchesLibopus
	DecoderExplicitHybridDREDDecodeSecondLossThenNextPacketAPIRateMatrixMatchesLibopus
	DecoderExplicitSecondLossThenNextPacketMatchesLibopus
	DecoderExplicitSecondLossThenNextPacket16kMatchesLibopus
	DecoderExplicitDREDDecodeFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeCELTSuperwidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeCELTWidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecode16kFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeSecondLossFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeSecondLossCELTSuperwidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeSecondLossCELTWidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacketFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacketCELTSuperwidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitDREDDecodeThenNextPacketCELTWidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitSecondLossThenNextPacketFrameSizeMatrixMatchesLibopus
	DecoderExplicitSecondLossThenNextPacketCELTSuperwidebandFrameSizeMatrixMatchesLibopus
	DecoderExplicitSecondLossThenNextPacketCELTWidebandFrameSizeMatrixMatchesLibopus
)
extra_controls_parity_decoder_root="$(test_regex "${extra_controls_parity_decoder_cases[@]}")"

gate_dnn_blob_parity() {
	# Default build: SetDNNBlob model loading is compile-gated like libopus
	# USE_WEIGHTS_FILE, so the default surface only exercises the no-op contract
	# and SupportsOptionalExtension probe.
	run_parity . -run 'TestSupportsOptionalExtension|ExampleSupportsOptionalExtension' -count=1
	run_parity . -run "$dnn_blob_default_root" -count=1
	run_parity ./multistream -run "$dnn_blob_default_multistream" -count=1
	# Tagged builds compile the model loaders; run the libopus model-blob parity
	# and retention tests under the DRED tag.
	run_tagged_parity "$tag_dred" . -run "$dnn_blob_tagged_root" -count=1
	run_tagged_parity "$tag_dred" . -run 'Test(DREDControlModelBlobsMatchPinnedLibopusDigests)' -count=1
	require_no_skips "DNN blob parity"
}

gate_dred_tag() {
	run_tagged_parity "$tag_dred" . -run 'Test(OptionalExtensionDocsContract|SupportsOptionalExtension|DREDBuildTagExposesSupportedTopLevelControls|DREDBuildPublicAPIContract|PublicDRED|Encoder_OptionalExtensionControls|MultistreamEncoder_OptionalExtensionControls)|ExampleSupportsOptionalExtension' -count=1
	run_tagged_parity "$tag_dred" . -run 'Test(DREDDecoderParseRequiresModel|DREDDecoderParseClearsStateWhenPacketHasNoDRED|DREDDecoderProcessRejectsEmptyState|DREDDecoderProcessDoesNotAllocate|DREDDecoderParseAndProcessDoesNotAllocate|DREDDecoderParseClearsStateOnMalformedPacket)' -count=1
	run_tagged_parity "$tag_dred" . -run 'Test(DREDDecoderParseAndProcessRetainsMetadata|StandaloneDREDParseMatchesLibopus)' -count=1
	run_tagged_parity "$tag_dred" . -run 'Test(StandaloneDREDProcessMatchesLibopusOnRealPacket|StandaloneDREDProcessMatchesLibopusOnQualityPacket|StandaloneDREDProcessLifecycleMatchesLibopusOnRealPacket)' -count=1
	run_tagged_parity "$tag_dred" . -run "Test($dred_recovery_window_root|StandaloneDREDRecoveryQueueMatchesLibopus)" -count=1
	run_tagged_parity "$tag_dred" . -run "$dred_payload_parser_root" -count=1
	run_tagged_parity "$tag_dred" ./internal/dred -count=1
	run_tagged_parity "$tag_dred" ./internal/dnnblob -run "$dred_reference_dnnblob" -count=1
	run_tagged_parity "$tag_dred" ./internal/dred/rdovae -run "$dred_reference_rdovae" -count=1
	run_tagged_parity "$tag_dred" . -run "$dred_decoder_dormancy_root" -count=1
	run_tagged_parity "$tag_dred" . -run "$dred_decoder_recovery_internal_root" -count=1
	run_tagged_parity "$tag_dred" . -run 'Test(DecoderCachedDREDRecoveryMatchesLibopusLifecycle|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kCELT|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kHybrid|DecoderCachedDREDRecoveryCursorTracksLosses16kCELT|DecoderCachedDREDRecoveryCursorTracksLosses16kHybrid|DecoderCachedDREDRecoveryCursorTracksLosses48kCELT|DecoderCachedDREDRecoveryCursorTracksLosses48kHybrid)' -count=1
	run_tagged_parity "$tag_dred" . -run "$dred_stereo_recovery_root" -count=1
	run_tagged_parity "$tag_dred" . -run "$dred_encoder_payload_root" -count=1
	run_tagged_parity "$tag_dred" ./encoder -run 'Test(DREDBitsTableMatchesLibopusReference|ComputeDREDEmissionPlanMatchesLibopusFormula|ComputeDREDEmissionPlanUsesFECControlFlag|DREDMaxChunksOnlyCapsVBR|DREDRuntimeBuildExposesEncoderControls|EncoderDREDDuration|EncoderResetClearsDREDDuration|EncoderDREDReadyRequiresModelAndDuration|EncoderDREDRuntimeStaysDormantUntilReady|EncoderDREDEncodingActiveRequiresModelAndDuration|EncoderEncodeKeepsDREDRuntimeDormantUntilDurationArmed|EncoderProcessDREDLatentsDoesNotAllocate|EncoderProcessDREDLatentsDoesNotAllocate48k|MaybeBuildSingleFrameDREDPacketCarriesExtension)' -count=1
	run_tagged_parity "$tag_dred" ./encoder -run "$dred_encoder_runtime_internal" -count=1
	run_tagged_parity "$tag_dred" ./multistream -run "$dred_multistream_dormancy" -count=1
	run_tagged_parity "$tag_dred" ./multistream -run "$dred_multistream_recovery_internal" -count=1
	run_tagged_parity "$tag_dred" ./multistream -run "Test(DREDBuildTagExposesEncoderControlsOnly|DecoderPublicSetDNNBlobDoesNotArmDREDDecoderWhenBlobContainsModel|$dred_multistream_neural_decodes)" -count=1
	require_no_skips "DRED tag"
}

gate_qext_parity() {
	run_tagged_parity "$tag_qext" . -run 'Test(OptionalExtensionDocsContract|SupportsOptionalExtension|QEXTBuildPublicAPIContract|QEXTBuildTagExposesSupportedTopLevelControls|Encoder_OptionalExtensionControls|MultistreamEncoder_OptionalExtensionControls|DecodeGopusQEXTPacketMatchesLibopus|DecodeLibopusQEXTPacketMatchesLibopus|DecodeLibopusQEXTPacketFinalRangeMatchesLibopus|DecodeLibopusQEXTPacketIgnoreExtensionsMatchesInactiveCELT|DecodeLibopusQEXTOpaquePaddingMatchesInactiveCELT|DecodeLibopusQEXTIgnoreExtensionsToggleSequenceMatchesExplicitPayloads|DecodeLibopusQEXTMultiFramePacketMatchesExplicitPayloads|DecodeLibopusQEXTMultiFrameIgnoreExtensionsMatchesInactivePayloads|DecodeLibopusQEXTPacketCELTFloat32FastPathMatchesFloat64|DecodeLibopusQEXTPacketWrapperMatchesDirectCELT|DecodeHybridLibopusQEXTPacketMatchesLibopus|DecodeHybridLibopusQEXTPacketIgnoreExtensionsMatchesInactiveHybrid|DecodeHybridLibopusQEXTOpaquePaddingMatchesInactiveHybrid|DecodeHybridLibopusQEXTIgnoreExtensionsToggleSequenceMatchesExplicitPayloads|DecodeStereoLibopusQEXTPacketToMonoMatchesLibopus|DecodeLibopusRestrictedCELTPacketMatchesLibopus|DecodeLibopusQEXTChannelTransitionSequenceMatchesLibopus)|ExampleSupportsOptionalExtension' -count=1
	run_tagged_parity "$tag_qext" . -run "$qext_packet_extension_root" -count=1
	run_parity ./internal/libopustooling -run "$qext_libopus_tooling" -count=1
	run_tagged_parity "$tag_qext" ./encoder ./celt ./multistream -run 'QEXT' -count=1
	run_tagged_parity "$tag_qext" ./multistream -run "$qext_packet_extension_multistream" -count=1
	run_tagged_parity "$tag_dred_qext" . -run 'Test(CombinedDREDQEXTBuildOptionalExtensionContract|CombinedDREDQEXTBuildPublicAPIContract|SupportsOptionalExtension)|ExampleSupportsOptionalExtension' -count=1
	run_tagged_parity "$tag_extra_controls_qext" . -run 'Test(QEXTExtraControlsBuildOptionalExtensionContract|QEXTExtraControlsBuildPublicAPIContract|SupportsOptionalExtension)|ExampleSupportsOptionalExtension' -count=1
	run_tagged_parity "$tag_all_optional" . -run 'TestSupportsOptionalExtension' -count=1
	require_no_skips "QEXT parity"
}

gate_core_oracles_parity() {
	run_parity . -run "$core_oracles_root" -count=1
	run_parity ./celt -run "$core_oracles_celt" -count=1
	run_parity ./internal/dnnmath -run "$core_oracles_dnnmath" -count=1
	run_parity ./encoder -run "$core_oracles_encoder" -count=1
	run_parity ./internal/lpcnetplc -run "$core_oracles_lpcnetplc" -count=1
	run_parity ./multistream -run "$core_oracles_multistream" -count=1
	run_parity ./internal/opusmath -run "$core_oracles_opusmath" -count=1
	run_parity ./rangecoding -run "$core_oracles_range" -count=1
	run_parity ./silk -run "$core_oracles_silk" -count=1
	require_no_skips "core oracles parity"
}

gate_doc_contract() {
	run_go_test_json . -run "$doc_contract_root" -count=1
	run_go_test_json ./testvectors -run "$doc_contract_testvectors" -count=1
}

gate_extra_controls_tag() {
	run_tagged_parity "$tag_extra_controls" . -run "$extra_controls_core_root" -count=1
	run_tagged_parity "$tag_extra_controls" . -run "$dred_payload_parser_root" -count=1
	run_tagged_parity "$tag_extra_controls" . -run "$dred_decoder_dormancy_root" -count=1
	run_tagged_parity "$tag_extra_controls" . -run "$dred_decoder_recovery_internal_root" -count=1
	run_tagged_parity "$tag_extra_controls" . -run "$dred_stereo_recovery_root" -count=1
	run_tagged_parity "$tag_extra_controls" ./encoder ./multistream -run 'Test(DREDRuntimeBuildExposesEncoderControls|EncoderDREDDuration|EncoderResetClearsDREDDuration|EncoderDREDReadyRequiresModelAndDuration|EncoderDREDEncodingActiveRequiresModelAndDuration|EncoderEncodeKeepsDREDRuntimeDormantUntilDurationArmed)' -count=1
	run_tagged_parity "$tag_extra_controls" ./encoder -run "$dred_encoder_runtime_internal" -count=1
	run_tagged_parity "$tag_extra_controls" ./multistream -run "$extra_controls_multistream_dormancy" -count=1
	run_tagged_parity "$tag_extra_controls" ./multistream -run "$dred_multistream_recovery_internal" -count=1
	run_tagged_parity "$tag_extra_controls" ./multistream -run "Test(DecoderPublicSetDNNBlobDoesNotArmDREDDecoderWhenBlobContainsModel|$dred_multistream_neural_decodes)" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred -run 'Test(EncodeExperimentalPayloadMatchesLibopus|EncodeExperimentalPayloadMatchesLibopusDelayedOffset|EncodeExperimentalPayloadMatchesLibopusMatrix)' -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dnnblob -run "$dred_reference_dnnblob" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred -run "$dred_reference_internal" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred/rdovae -run "$dred_reference_rdovae" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred -run "$dred_latents_trace" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/lpcnetplc -run 'Test(PredictorMatchesLibopusOnRealModel|FARGANConditionerMatchesLibopusOnRealModel|FARGANPrimeContinuityMatchesLibopusOnRealModel|FARGANSynthesizeMatchesLibopusOnRealModel|LPCNetDREDSequenceMatchesLibopusTightly|MarkUpdatedFrameFloatMatchesLibopus|MarkUpdatedFrameInt16MatchesLibopus|PrefillAndConcealmentFeatureStepMatchLibopus|BoundedConcealFrameFloatMatchesLibopus|ConcealFrameFloatWithAnalysisMatchesLibopusColdStart)' -count=1
	require_no_skips "extra-controls tag"
}

gate_extra_controls_parity() {
	run_tagged_parity "$tag_extra_controls" . -run "$extra_controls_parity_root" -count=1
	run_tagged_parity "$tag_extra_controls" . -run 'Test(OSCEBWEForwardPassMatchesLibopusNumericalParity|OSCEBWERawSignalNetMatchesLibopus|OSCEBWEForwardPassPLCContinuityMatchesLibopus|OSCEBWECrossFade10msMatchesLibopus|OSCEBWEModelForwardPassMatchesLibopus|OSCEBWEInt8LibopusKernelParity|OSCEBWEForwardPassInt8KernelReproducible|OSCELACEForwardPassMatchesLibopus|DecoderOSCEFloatToInt16MatchesLibopusScaleOutput|DecoderOSCEBWERuntimeIntegration|DecoderOSCELACERuntimeIntegration|DecoderOSCEBWECrossFadeTransition|DecoderOSCEBWEPLC|DecoderOSCELACECrossFadeTransition|DecoderOSCELACEPLC|MultistreamDecoderOSCEBWELACERuntimeIntegration|MultistreamDecoderOSCEBWEMatchesSingleStreamDecoder|MultistreamDecoderOSCELACEFeedsPublicPCM|MultistreamDecoderOSCELACEMatchesSingleStreamDecoder)' -count=1
	run_tagged_parity "$tag_extra_controls" ./multistream -run 'TestStreamOSCEFloatToInt16MatchesLibopusScaleOutput' -count=1
	run_tagged_parity "$tag_extra_controls" ./multistream -run "Test($dred_multistream_neural_decodes)" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dnnblob -run "$dred_reference_dnnblob" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred -run "$dred_reference_internal" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred/rdovae -run "$dred_reference_rdovae" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred -run "Test(ConvertTo16kMonoFloat64MatchesLibopus|ConvertTo16kMonoFloat64MatchesLibopusAcrossCalls|EncodeExperimentalPayloadMatchesLibopusMatrix|EncodeExperimentalPayloadMatchesLibopusLargeLaplaceContinuation)|$dred_rdovae_real_model" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/dred -run "$dred_latents_trace" -count=1
	run_tagged_parity "$tag_extra_controls" ./internal/lpcnetplc -run 'Test(LPCNetSingleFrameFeaturesFloatMatchesLibopusColdStart|LPCNetSingleFrameFeaturesFloatMatchesLibopusStatefulSequence|LPCNetDREDSequenceMatchesLibopusTightly|BurgCepstralAnalysisMatchesLibopus|PitchDNNMatchesLibopusOnRealModel|MarkUpdatedFrameInt16MatchesLibopus|ConcealFrameFloatWithAnalysisMatchesLibopus)' -count=1
	run_tagged_parity "$tag_extra_controls" . -run "$dred_encoder_payload_root" -count=1
	run_tagged_parity "$tag_extra_controls" . -run 'Test(DecoderExplicitDREDFirstConcealFrameBootstraps48kRuntime|DecoderExplicitDREDThreeConcealFramesBootstraps48kRuntime|DecoderExplicitDREDThreeConcealFramesManualStep48kRuntime|DecoderExplicitDREDThreeConcealFramesMixedHelpers48kRuntime)' -count=1
	run_tagged_parity "$tag_extra_controls" . -run "$dred_stereo_recovery_root" -count=1
	run_tagged_parity "$tag_extra_controls" . -run "$extra_controls_parity_silk_dred_root" -count=1
	require_no_skips "extra-controls parity"
}

gate_quality() {
	run_parity ./testvectors -run "$quality_testvectors" -count=1 -v
}

gate_exactness() {
	run_exactness ./encoder -run "$exactness_encoder" -count=1
}

gate_exhaustive() {
	run_exhaustive ./testvectors -run "$exhaustive_testvectors" -count=1 -timeout=30m
}

gate_provenance() {
	run_exhaustive ./testvectors -run "$provenance_testvectors" -count=1 -timeout=30m
}

usage() {
	echo "usage: $0 {doc-contract|dnn-blob-parity|core-oracles-parity|quality|exactness|exhaustive|provenance|dred-tag|qext-parity|extra-controls-tag|extra-controls-parity}"
}

case "${1:-}" in
	doc-contract)
		gate_doc_contract
		;;
	dnn-blob-parity)
		gate_dnn_blob_parity
		;;
	core-oracles-parity)
		gate_core_oracles_parity
		;;
	quality)
		gate_quality
		;;
	exactness)
		gate_exactness
		;;
	exhaustive)
		gate_exhaustive
		;;
	provenance)
		gate_provenance
		;;
	dred-tag)
		gate_dred_tag
		;;
	qext-parity)
		gate_qext_parity
		;;
	extra-controls-tag)
		gate_extra_controls_tag
		;;
	extra-controls-parity)
		gate_extra_controls_parity
		;;
	*)
		usage
		exit 2
		;;
esac
