#!/usr/bin/env bash
set -euo pipefail

GO_BIN="${GO:-go}"
GO_WORK_ENV="${GO_WORK_ENV:-GOWORK=off}"
go_env=()
if [[ -n "$GO_WORK_ENV" ]]; then
	# Makefile passes GO_WORK_ENV as simple KEY=VALUE assignments.
	# shellcheck disable=SC2206
	go_env=($GO_WORK_ENV)
fi

json_out="$(mktemp)"
json_part="$json_out.part"
trap 'rm -f "$json_out" "$json_part"' EXIT

run_json() {
	if ! "$@" >"$json_part"; then
		cat "$json_part"
		cat "$json_part" >>"$json_out"
		exit 1
	fi
	cat "$json_part"
	cat "$json_part" >>"$json_out"
	: >"$json_part"
}

run_parity() {
	run_json env GOPUS_TEST_TIER=parity GOPUS_STRICT_LIBOPUS_REF=1 "${go_env[@]}" "$GO_BIN" test -json "$@"
}

require_no_skips() {
	local label="$1"
	if grep -q '"Action":"skip"' "$json_out"; then
		echo "Unexpected skip detected in required $label gate:"
		grep '"Action":"skip"' "$json_out"
		exit 1
	fi
}

dnn_blob_default_root='Test(DefaultBuildDNNBlobKeepsDREDRuntimeDormant|DefaultBuildEncoderDNNBlobKeepsDREDDormant|HotPathAllocsDecodePLCDNNReadyAtMostBaseline|EncoderSetDNNBlobRetainedAcrossReset|DecoderSetDNNBlobRetainedAcrossReset|DecoderSetDNNBlobStereoRuntimeRetainedAcrossReset|MultistreamEncoderSetDNNBlobRetainedAcrossReset|MultistreamDecoderSetDNNBlobRetainedAcrossReset|ValidEncoderTestDNNBlobShape|ValidDecoderTestDNNBlobShape)'
dnn_blob_default_multistream='Test(DefaultBuildMultistreamDecoderRealBlobDormant|DefaultBuildMultistreamDecoderDecodeAllocGuard|DefaultBuildMultistreamEncoderDNNBlobKeepsAllocsFlat)'
dred_reference_internal='Test(DREDConstantsMatchLibopusReference|DREDStatsTablesMatchLibopusReference|DREDRDOVAEModelBlobsMatchPinnedLibopusDigests)'
dred_reference_dnnblob='Test(DNNBlobConstantsMatchLibopusReference|DREDModelManifestsMatchLibopusReference)'
dred_reference_rdovae='Test(RDOVAELayerSpecsMatchLibopusReference)'
dred_rdovae_real_model='Test(RDOVAEEncoderMatchesLibopusOnRealModel|RDOVAEDecoderMatchesLibopusOnRealModel)'
extra_controls_core_root='Test(SupportsOptionalExtension|ExtraControlsBuildExposesTopLevelControls|ExtraControlsBuildPublicAPIContract|PublicDRED|DREDDecoderParseRequiresModel|DREDDecoderParseAndProcessRetainsMetadata|DREDDecoderParseClearsStateWhenPacketHasNoDRED|DREDDecoderParseClearsStateOnMalformedPacket|StandaloneDREDParseMatchesLibopus|StandaloneDREDProcessMatchesLibopusOnRealPacket|StandaloneDREDProcessLifecycleMatchesLibopusOnRealPacket|StandaloneDREDRecoveryWindowMatchesLibopus|StandaloneDREDRecoveryQueueMatchesLibopus|DecoderCoreDNNBlobDoesNotArmGoodPacketDREDWork|DecoderCachedDREDRecoveryMatchesLibopusLifecycle|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kCELT|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kHybrid|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses48kCELT|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses48kHybrid|DecoderExplicitDREDWarmup48kStateMatchesLibopus)|ExampleSupportsOptionalExtension'
dred_stereo_recovery_root='Test(DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kCELTStereo|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses48kCELTStereo|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses48kHybridStereo)'
dred_latents_trace='TestLibopusDREDLatentsTraceStereoDivergesFromMono'
dred_decoder_dormancy_root='Test(DecoderCoreDNNBlobDoesNotArmGoodPacketDREDWork|NewDecoderLeavesDREDPayloadBufferDormant|StandaloneDREDArmKeepsRecoveryNeuralAnd48kBridgeDormant|MainDecoderDNNBlobKeepsRecoveryAndPayloadDormant|MainDecoder48kDNNBlobKeepsRecoveryAndBridgeDormant|MainDecoder16kDNNBlobGoodDecodeKeepsRecoveryDormantUntilLoss|MainDecoder48kDNNBlobGoodDecodeKeepsRecoveryDormantUntilLoss|MainDecoder48kDNNBlobGoodSILKHybridDecodeKeepsRecoveryDormantUntilLoss|ClearingStandaloneDREDPreservesMainNeuralState|DecoderCachesDREDPayloadWhenDREDModelLoaded|DecoderCachesDREDSampleTimingForLaterFrame|DecoderLeavesDREDPayloadDormantWithoutDREDModel|DecoderLeavesDREDStateDormantWithoutAnySidecar|PublicDecoderSetDNNBlobDoesNotArmDREDDecoderWhenBlobContainsModel|DecoderLeavesDREDPayloadDormantWhenIgnoringExtensions|DecoderDREDCacheFollowsStandaloneModelAndIgnoreExtensions|DecoderResetDropsActivatedDREDRuntimeBackToDormant)'
dred_decoder_recovery_internal_root='Test(DecoderDREDRecoveryBlendFollowsLifecycle|DecoderMarkDREDUpdatedPCMRefreshesNeuralHistory|DecoderMarkDREDUpdatedPCMCELTKeepsBridgeOwnedHistory|DecoderMarkDREDUpdatedPCMDormantWithoutSidecar|DecoderMarkDREDUpdatedPCMDoesNotTrackHistoryWithoutNeuralConcealment|DecoderPrimeDREDCELTEntryHistoryUsesCELTBridge|DecoderPrimeDREDCELTEntryHistoryStaysDormantWithoutNeuralConcealment|DecoderDecodePLCAppliesNeuralConcealmentWhenReady)'
dred_encoder_runtime_internal='Test(EncoderDREDInitialLatentsTraceMatchesLibopus|EncoderDREDLongCELTLatentsUseLibopusSubframeCadence|EncoderProcessDREDLatentsDownmixesStereo16k|EncoderProcessDREDLatentsSupportsRateConversion|EncoderProcessDREDLatentsBuffers48k10msFrames|EncoderProcessDREDLatentsTracksHistoryWindow|EncoderProcessDREDLatentsTracksOffsets|EncoderBuildDREDExperimentalPayloadUsesRuntimeHistory|EncoderBuildDREDExperimentalPayloadDoesNotAllocate|EncoderSetDREDDurationGrowsScratchPacketWhenArmed)'
dred_payload_parser_root='TestFindDREDPayload'
dred_quality_root='TestExplicitDRED(ImprovesConcealedAudioQualityAtSixtyPercentLoss|QualityTracksLibopusAtSixtyPercentLoss)'
dred_multistream_dormancy='Test(NewDecoderLeavesDREDSidecarDormant|DecoderCachesDREDPayloadPerStreamWhenModelLoaded|DecoderCachesDREDSampleTimingForLaterStreamFrame|DecoderLeavesDREDPayloadDormantWithoutDREDModel|DecoderLeavesDREDStateDormantWithoutAnySidecar|DecoderLeavesDREDStateDormantWithOnlyMainDNNBlob|DecoderLeavesDREDPayloadDormantWhenIgnoringExtensions|DecoderDREDCacheFollowsStandaloneModelAndIgnoreExtensions|DecoderDoesNotCachePartialDREDStateWhenLaterStreamFails|DREDBuildTagExposesEncoderControlsOnlyReadyRequiresEveryStream)'
extra_controls_multistream_dormancy='Test(NewDecoderLeavesDREDSidecarDormant|DecoderCachesDREDPayloadPerStreamWhenModelLoaded|DecoderCachesDREDSampleTimingForLaterStreamFrame|DecoderLeavesDREDPayloadDormantWithoutDREDModel|DecoderLeavesDREDStateDormantWithoutAnySidecar|DecoderLeavesDREDStateDormantWithOnlyMainDNNBlob|DecoderLeavesDREDPayloadDormantWhenIgnoringExtensions|DecoderDREDCacheFollowsStandaloneModelAndIgnoreExtensions|DecoderDoesNotCachePartialDREDStateWhenLaterStreamFails|EncoderDREDReadyRequiresModelAndDurationOnEveryStream)'
dred_multistream_recovery_internal='TestDecoderDREDRecoveryBlendFollowsLifecycle'
qext_packet_extension_root='Test(GeneratePacketExtensionsMatchesLibopusCases|PacketExtensionIteratorParseAndCount|PacketExtensionIteratorRepeatExpansion|PacketExtensionIteratorRejectsInvalidSeparator|MultistreamPacketPadUnpadSelfDelimitedRoundTrip|MultistreamPacketPadUnpadThreeStreamsRoundTrip|RepacketizerPreservesPacketExtensions|PacketPadPreservesPacketExtensions|SelfDelimitedPacketPreservesPacketExtensions|DecodeSelfDelimitedPacketPreservesOpaqueMalformedPadding)'
qext_packet_extension_multistream='Test(SelfDelimitedPacketPreservesPacketExtensions|DecodeSelfDelimitedPacketPreservesOpaqueMalformedPadding)'
qext_libopus_tooling='TestFindQEXTLibopusToolForOSUsesSeparateSourceTree'
core_oracles_celt='TestCELT(Log2|Exp2)MatchesLibopusFloatApprox|TestCELTBitexact(Cos|Log2Tan)MatchesLibopus|TestCELTIntegerMathMatchesLibopus'
core_oracles_silk='TestSILK(Lin2Log|Log2Lin|Fixed|NLSF|A2|NLSF2A|Gains|Stereo|LTP|QuantLTPGains)'
core_oracles_range='TestRangeCoderMatchesLibopusOracle'
extra_controls_parity_root='Test(ParsedDREDAvailabilityMatchesLibopus)'
extra_controls_parity_silk_dred_root='Test(DecoderExplicitSILKDREDDecodeMatchesLibopus|DecoderExplicit16kSILKDREDDecodeMatchesLibopus)'
extra_controls_parity_decoder_root='Test(DecoderCachedDREDDecodeMatrixMatchesLiveSequenceOracle|DecoderCachedStereoDREDDecodeMatchesLiveSequenceOracle|DecoderCachedStereoDREDCELTMatrixMatchesLiveSequenceOracle|DecoderCachedStereoDREDHybridMatrixMatchesLiveSequenceOracle|DecoderCachedStereoDREDSecondLossMatchesLiveSequenceOracle|DecoderCachedStereoDREDThenNextPacketMatchesLiveSequenceOracle|DecoderCachedStereoDREDSecondLossThenNextPacketMatchesLiveSequenceOracle|DecoderCachedDREDDecodeCELTSuperwidebandMatrixMatchesLiveSequenceOracle|DecoderCachedDREDDecodeCELTWidebandMatrixMatchesLiveSequenceOracle|DecoderCachedDREDThenNextPacketMatchesLiveSequenceOracle|DecoderCachedDREDThenNextPacketCELTSuperwidebandMatchesLiveSequenceOracle|DecoderCachedDREDThenNextPacketCELTWidebandMatchesLiveSequenceOracle|DecoderCachedDREDSecondLossMatchesLiveSequenceOracle|DecoderCachedDREDSecondLossCELTSuperwidebandMatchesLiveSequenceOracle|DecoderCachedDREDSecondLossCELTWidebandMatchesLiveSequenceOracle|DecoderCachedDREDSecondLossThenNextPacketMatchesLiveSequenceOracle|DecoderCachedDREDSecondLossThenNextPacketCELTSuperwidebandMatchesLiveSequenceOracle|DecoderCachedDREDSecondLossThenNextPacketCELTWidebandMatchesLiveSequenceOracle|DecoderCachedHybridDREDDecodeMatrixMatchesLiveSequenceOracle|DecoderCachedHybridDRED16kDecodeMatrixMatchesLiveSequenceOracle|DecoderCachedHybridDREDThenNextPacketMatchesLiveSequenceOracle|DecoderCachedHybridDRED16kThenNextPacketMatchesLiveSequenceOracle|DecoderCachedHybridDREDSecondLossMatchesLiveSequenceOracle|DecoderCachedHybridDRED16kSecondLossMatchesLiveSequenceOracle|DecoderCachedHybridSecondLossThenNextPacketMatchesLiveSequenceOracle|DecoderCachedHybridDRED16kSecondLossThenNextPacketMatchesLiveSequenceOracle|DecoderFirstLossNeuralConcealmentMatchesLiveSequenceOracle|DecoderFirstLossNeuralConcealment16kFrameSizeMatrixMatchesLiveSequenceOracle|DecoderFirstLossThenNextPacketMatchesLiveSequenceOracle|DecoderFirstLossThenNextPacket16kFrameSizeMatrixMatchesLiveSequenceOracle|DecoderSecondLossNeuralConcealmentMatchesLiveSequenceOracle|DecoderSecondLossNeuralConcealment16kFrameSizeMatrixMatchesLiveSequenceOracle|DecoderSecondLossThenNextPacketMatchesLiveSequenceOracle|DecoderSecondLossThenNextPacket16kFrameSizeMatrixMatchesLiveSequenceOracle|DecoderExplicitDREDCELT48kBridgeMatchesLibopusFirstLoss|DecoderExplicitDREDCELT48kBridgeMatchesLibopusSecondLoss|DecoderExplicitDREDDecodeMatchesLibopus|DecoderExplicitStereoDREDDecodeMatchesLibopus|DecoderExplicitStereoDRED16kDecodeMatchesLibopus|DecoderExplicitStereoHybridDRED16kDecodeMatchesLibopus|DecoderExplicitSILKDREDDecodeStereoMatchesLibopus|DecoderExplicitDREDDecode16kMatchesLibopus|DecoderExplicitDREDDecode16kCELTSuperwidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecode16kCELTWidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeSecondLossMatchesLibopus|DecoderExplicitDREDDecodeSecondLossGainTransitionMatchesLibopus|DecoderExplicitDREDDecodeSecondLoss16kMatchesLibopus|DecoderExplicitDREDDecodeOffsetMatrixMatchesLibopus|DecoderExplicitDREDDecodeOffsetMatrixCELTSuperwidebandMatchesLibopus|DecoderExplicitDREDDecodeOffsetMatrixHybridSuperwidebandMatchesLibopus|DecoderExplicitDREDDecodeOffsetMatrixHybridFullbandMatchesLibopus|DecoderExplicitDREDDecodeOffsetMatrix16kHybridMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacketMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacket16kMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacket16kFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacket16kCELTSuperwidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacket16kCELTWidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitHybridDREDDecodeMatrixMatchesLibopus|DecoderExplicitHybridDREDDecode16kMatrixMatchesLibopus|DecoderExplicit16kHybridDREDDecodeMatrixMatchesLibopus|DecoderExplicitHybridDREDDecodeThenNextPacketMatchesLibopus|DecoderExplicitHybridDREDDecodeThenNextPacket16kMatchesLibopus|DecoderExplicitHybridDREDDecodeSecondLossMatrixMatchesLibopus|DecoderExplicitHybridDREDDecodeSecondLoss16kMatrixMatchesLibopus|DecoderExplicitHybridDREDDecodeSecondLossThenNextPacketMatrixMatchesLibopus|DecoderExplicitHybridDREDDecodeSecondLossThenNextPacket16kMatrixMatchesLibopus|DecoderExplicitSecondLossThenNextPacketMatchesLibopus|DecoderExplicitSecondLossThenNextPacket16kMatchesLibopus|DecoderExplicitDREDDecodeFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeCELTSuperwidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeCELTWidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecode16kFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeSecondLossFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeSecondLossCELTSuperwidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeSecondLossCELTWidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacketFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacketCELTSuperwidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitDREDDecodeThenNextPacketCELTWidebandFrameSizeMatrixMatchesLibopus|DecoderExplicitSecondLossThenNextPacketFrameSizeMatrixMatchesLibopus|DecoderExplicitSecondLossThenNextPacketCELTWidebandFrameSizeMatrixMatchesLibopus)'

gate_dnn_blob_parity() {
	run_parity . -run 'Test(DNNBlobControlAcceptsLibopusModelBlobs|SupportsOptionalExtension)|ExampleSupportsOptionalExtension' -count=1
	run_parity -tags gopus_dred . -run 'Test(DREDControlModelBlobsMatchPinnedLibopusDigests)' -count=1
	run_parity . -run "$dnn_blob_default_root" -count=1
	run_parity ./multistream -run "$dnn_blob_default_multistream" -count=1
	require_no_skips "DNN blob parity"
}

gate_dred_tag() {
	run_parity -tags gopus_dred . -run 'Test(OptionalExtensionDocsContract|SupportsOptionalExtension|DREDBuildTagExposesSupportedTopLevelControls|DREDBuildPublicAPIContract|PublicDRED|Encoder_OptionalExtensionControls|MultistreamEncoder_OptionalExtensionControls)|ExampleSupportsOptionalExtension' -count=1
	run_parity -tags gopus_dred . -run 'Test(DREDDecoderParseRequiresModel|DREDDecoderParseClearsStateWhenPacketHasNoDRED|DREDDecoderProcessRejectsEmptyState|DREDDecoderProcessDoesNotAllocate|DREDDecoderParseAndProcessDoesNotAllocate|DREDDecoderParseClearsStateOnMalformedPacket)' -count=1
	run_parity -tags gopus_dred . -run 'Test(DREDDecoderParseAndProcessRetainsMetadata|StandaloneDREDParseMatchesLibopus)' -count=1
	run_parity -tags gopus_dred . -run 'Test(StandaloneDREDProcessMatchesLibopusOnRealPacket|StandaloneDREDProcessLifecycleMatchesLibopusOnRealPacket)' -count=1
	run_parity -tags gopus_dred . -run 'Test(StandaloneDREDRecoveryWindowMatchesLibopus|StandaloneDREDRecoveryQueueMatchesLibopus)' -count=1
	run_parity -tags gopus_dred . -run "$dred_payload_parser_root" -count=1
	run_parity -tags gopus_dred ./internal/dred -count=1
	run_parity -tags gopus_dred ./internal/dnnblob -run "$dred_reference_dnnblob" -count=1
	run_parity -tags gopus_dred ./internal/dred/rdovae -run "$dred_reference_rdovae" -count=1
	run_parity -tags gopus_dred . -run "$dred_decoder_dormancy_root" -count=1
	run_parity -tags gopus_dred . -run "$dred_decoder_recovery_internal_root" -count=1
	run_parity -tags gopus_dred . -run "$dred_quality_root" -count=1
	run_parity -tags gopus_dred . -run 'Test(DecoderCachedDREDRecoveryMatchesLibopusLifecycle|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kCELT|DecoderCachedDREDRecoveryMatchesLibopusLifecycle48kHybrid|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses48kCELT|DecoderCachedDREDRecoveryCursorStaysIdleAcrossLosses48kHybrid)' -count=1
	run_parity -tags gopus_dred . -run "$dred_stereo_recovery_root" -count=1
	run_parity -tags gopus_dred . -run 'Test(EncoderCarriedDREDPayloadMatchesLibopusCELTFullband20msStereo|EncoderSilkMono20msPrimaryFrameByteExactMatchesLibopus|EncoderSilkMono40msPrimaryFrameByteExactMatchesLibopus|EncoderSilkMono60msPrimaryFrameByteExactMatchesLibopus|EncoderSilkStereo20msPrimaryFrameByteExactMatchesLibopus|EncoderCarriedDREDPayloadMatchesLibopusCELTFullband20ms|EncoderCarriedDREDPayloadMatchesLibopusCELTFullbandLongFrames|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msCBR|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband40ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband60ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWidebandLongFrames|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20ms|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40ms|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msStereo|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msStereoPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msStereo|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msStereo|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband40msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusCELTFullband20msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msStereo)' -count=1
	run_parity -tags gopus_dred ./encoder -run 'Test(DREDBitsTableMatchesLibopusReference|ComputeDREDEmissionPlanMatchesLibopusFormula|ComputeDREDEmissionPlanUsesFECControlFlag|DREDMaxChunksOnlyCapsVBR|DREDRuntimeBuildExposesEncoderControls|EncoderDREDDuration|EncoderResetClearsDREDDuration|EncoderDREDReadyRequiresModelAndDuration|EncoderDREDRuntimeStaysDormantUntilReady|EncoderDREDEncodingActiveRequiresModelAndDuration|EncoderEncodeKeepsDREDRuntimeDormantUntilDurationArmed|EncoderProcessDREDLatentsDoesNotAllocate|EncoderProcessDREDLatentsDoesNotAllocate48k|MaybeBuildSingleFrameDREDPacketCarriesExtension)' -count=1
	run_parity -tags gopus_dred ./encoder -run "$dred_encoder_runtime_internal" -count=1
	run_parity -tags gopus_dred ./multistream -run "$dred_multistream_dormancy" -count=1
	run_parity -tags gopus_dred ./multistream -run "$dred_multistream_recovery_internal" -count=1
	run_parity -tags gopus_dred ./multistream -run 'Test(DREDBuildTagExposesEncoderControlsOnly|DecoderPublicSetDNNBlobDoesNotArmDREDDecoderWhenBlobContainsModel|DecoderDecodeNilConsumesMultistreamDREDNeuralStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondCoupledStream)' -count=1
	require_no_skips "DRED tag"
}

gate_qext_parity() {
	run_parity -tags gopus_qext . -run 'Test(OptionalExtensionDocsContract|SupportsOptionalExtension|QEXTBuildPublicAPIContract|QEXTBuildTagExposesSupportedTopLevelControls|Encoder_OptionalExtensionControls|MultistreamEncoder_OptionalExtensionControls|DecodeGopusQEXTPacketMatchesLibopus|DecodeLibopusQEXTPacketMatchesLibopus|DecodeLibopusQEXTPacketFinalRangeMatchesLibopus|DecodeLibopusQEXTPacketIgnoreExtensionsMatchesInactiveCELT|DecodeLibopusQEXTOpaquePaddingMatchesInactiveCELT|DecodeLibopusQEXTIgnoreExtensionsToggleSequenceMatchesExplicitPayloads|DecodeLibopusQEXTMultiFramePacketMatchesExplicitPayloads|DecodeLibopusQEXTMultiFrameIgnoreExtensionsMatchesInactivePayloads|DecodeLibopusQEXTPacketCELTFloat32FastPathMatchesFloat64|DecodeLibopusQEXTPacketWrapperMatchesDirectCELT|DecodeHybridLibopusQEXTPacketMatchesLibopus|DecodeHybridLibopusQEXTPacketIgnoreExtensionsMatchesInactiveHybrid|DecodeHybridLibopusQEXTOpaquePaddingMatchesInactiveHybrid|DecodeHybridLibopusQEXTIgnoreExtensionsToggleSequenceMatchesExplicitPayloads|DecodeStereoLibopusQEXTPacketToMonoMatchesLibopus|DecodeLibopusRestrictedCELTPacketMatchesLibopus|DecodeLibopusQEXTChannelTransitionSequenceMatchesLibopus)|ExampleSupportsOptionalExtension' -count=1
	run_parity -tags gopus_qext . -run "$qext_packet_extension_root" -count=1
	run_parity ./internal/libopustooling -run "$qext_libopus_tooling" -count=1
	run_parity -tags gopus_qext ./encoder ./celt ./multistream -run 'QEXT' -count=1
	run_parity -tags gopus_qext ./multistream -run "$qext_packet_extension_multistream" -count=1
	run_parity -tags 'gopus_dred gopus_qext' . -run 'Test(CombinedDREDQEXTBuildOptionalExtensionContract|CombinedDREDQEXTBuildPublicAPIContract|SupportsOptionalExtension)|ExampleSupportsOptionalExtension' -count=1
	run_parity -tags 'gopus_extra_controls gopus_qext' . -run 'Test(QEXTExtraControlsBuildOptionalExtensionContract|QEXTExtraControlsBuildPublicAPIContract|SupportsOptionalExtension)|ExampleSupportsOptionalExtension' -count=1
	run_parity -tags 'gopus_dred gopus_extra_controls gopus_qext' . -run 'TestSupportsOptionalExtension' -count=1
	require_no_skips "QEXT parity"
}

gate_core_oracles_parity() {
	run_parity ./celt -run "$core_oracles_celt" -count=1
	run_parity ./rangecoding -run "$core_oracles_range" -count=1
	run_parity ./silk -run "$core_oracles_silk" -count=1
	require_no_skips "core oracles parity"
}

gate_extra_controls_tag() {
	run_parity -tags gopus_extra_controls . -run "$extra_controls_core_root" -count=1
	run_parity -tags gopus_extra_controls . -run "$dred_payload_parser_root" -count=1
	run_parity -tags gopus_extra_controls . -run "$dred_decoder_dormancy_root" -count=1
	run_parity -tags gopus_extra_controls . -run "$dred_decoder_recovery_internal_root" -count=1
	run_parity -tags gopus_extra_controls . -run "$dred_quality_root" -count=1
	run_parity -tags gopus_extra_controls . -run "$dred_stereo_recovery_root" -count=1
	run_parity -tags gopus_extra_controls ./encoder ./multistream -run 'Test(DREDRuntimeBuildExposesEncoderControls|EncoderDREDDuration|EncoderResetClearsDREDDuration|EncoderDREDReadyRequiresModelAndDuration|EncoderDREDEncodingActiveRequiresModelAndDuration|EncoderEncodeKeepsDREDRuntimeDormantUntilDurationArmed)' -count=1
	run_parity -tags gopus_extra_controls ./encoder -run "$dred_encoder_runtime_internal" -count=1
	run_parity -tags gopus_extra_controls ./multistream -run "$extra_controls_multistream_dormancy" -count=1
	run_parity -tags gopus_extra_controls ./multistream -run "$dred_multistream_recovery_internal" -count=1
	run_parity -tags gopus_extra_controls ./multistream -run 'Test(DecoderPublicSetDNNBlobDoesNotArmDREDDecoderWhenBlobContainsModel|DecoderDecodeNilConsumesMultistreamDREDNeuralStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondCoupledStream)' -count=1
	run_parity -tags gopus_extra_controls ./internal/dred -run 'Test(EncodeExperimentalPayloadMatchesLibopus|EncodeExperimentalPayloadMatchesLibopusDelayedOffset|EncodeExperimentalPayloadMatchesLibopusMatrix)' -count=1
	run_parity -tags gopus_extra_controls ./internal/dnnblob -run "$dred_reference_dnnblob" -count=1
	run_parity -tags gopus_extra_controls ./internal/dred -run "$dred_reference_internal" -count=1
	run_parity -tags gopus_extra_controls ./internal/dred/rdovae -run "$dred_reference_rdovae" -count=1
	run_parity -tags gopus_extra_controls ./internal/dred -run "$dred_latents_trace" -count=1
	run_parity -tags gopus_extra_controls ./internal/lpcnetplc -run 'Test(PredictorMatchesLibopusOnRealModel|FARGANConditionerMatchesLibopusOnRealModel|FARGANPrimeContinuityMatchesLibopusOnRealModel|FARGANSynthesizeMatchesLibopusOnRealModel|LPCNetDREDSequenceMatchesLibopusTightly|MarkUpdatedFrameFloatMatchesLibopus|MarkUpdatedFrameInt16MatchesLibopus|PrefillAndConcealmentFeatureStepMatchLibopus|BoundedConcealFrameFloatMatchesLibopus|ConcealFrameFloatWithAnalysisMatchesLibopusColdStart)' -count=1
	require_no_skips "extra-controls tag"
}

gate_extra_controls_parity() {
	run_parity -tags gopus_extra_controls . -run "$extra_controls_parity_root" -count=1
	run_parity -tags gopus_extra_controls . -run 'Test(OSCEBWEForwardPassMatchesLibopusNumericalParity|OSCEBWERawSignalNetMatchesLibopus|OSCEBWEForwardPassPLCContinuityMatchesLibopus|OSCEBWECrossFade10msMatchesLibopus|OSCEBWEModelForwardPassMatchesLibopus|OSCEBWEInt8LibopusKernelParity|OSCEBWEForwardPassInt8KernelReproducible|OSCELACEForwardPassMatchesLibopus|DecoderOSCEFloatToInt16MatchesLibopusScaleOutput|DecoderOSCEBWERuntimeIntegration|DecoderOSCELACERuntimeIntegration|DecoderOSCEBWECrossFadeTransition|DecoderOSCEBWEPLC|DecoderOSCELACECrossFadeTransition|DecoderOSCELACEPLC|MultistreamDecoderOSCEBWELACERuntimeIntegration|MultistreamDecoderOSCEBWEMatchesSingleStreamDecoder|MultistreamDecoderOSCELACEFeedsPublicPCM|MultistreamDecoderOSCELACEMatchesSingleStreamDecoder)' -count=1
	run_parity -tags gopus_extra_controls ./multistream -run 'TestStreamOSCEFloatToInt16MatchesLibopusScaleOutput' -count=1
	run_parity -tags gopus_extra_controls ./multistream -run 'Test(DecoderDecodeNilConsumesMultistreamDREDNeuralStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKNonFinalMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondMonoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralCELTFinalSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralHybridFinalSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalStereoStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKSecondCoupledStream|DecoderDecodeNilConsumesMultistreamDREDNeuralSILKFinalSecondCoupledStream)' -count=1
	run_parity -tags gopus_extra_controls ./internal/dnnblob -run "$dred_reference_dnnblob" -count=1
	run_parity -tags gopus_extra_controls ./internal/dred -run "$dred_reference_internal" -count=1
	run_parity -tags gopus_extra_controls ./internal/dred/rdovae -run "$dred_reference_rdovae" -count=1
	run_parity -tags gopus_extra_controls ./internal/dred -run "Test(ConvertTo16kMonoFloat64MatchesLibopus|ConvertTo16kMonoFloat64MatchesLibopusAcrossCalls|EncodeExperimentalPayloadMatchesLibopusMatrix|EncodeExperimentalPayloadMatchesLibopusLargeLaplaceContinuation)|$dred_rdovae_real_model" -count=1
	run_parity -tags gopus_extra_controls ./internal/dred -run "$dred_latents_trace" -count=1
	run_parity -tags gopus_extra_controls ./internal/lpcnetplc -run 'Test(LPCNetSingleFrameFeaturesFloatMatchesLibopusColdStart|LPCNetSingleFrameFeaturesFloatMatchesLibopusStatefulSequence|LPCNetDREDSequenceMatchesLibopusTightly|BurgCepstralAnalysisMatchesLibopus|PitchDNNMatchesLibopusOnRealModel|MarkUpdatedFrameInt16MatchesLibopus|ConcealFrameFloatWithAnalysisMatchesLibopus)' -count=1
	run_parity -tags gopus_extra_controls . -run 'Test(EncoderCarriedDREDPayloadMatchesLibopusCELTFullband20msStereo|EncoderSilkMono20msPrimaryFrameByteExactMatchesLibopus|EncoderSilkMono40msPrimaryFrameByteExactMatchesLibopus|EncoderSilkMono60msPrimaryFrameByteExactMatchesLibopus|EncoderSilkStereo20msPrimaryFrameByteExactMatchesLibopus|EncoderCarriedDREDPayloadMatchesLibopusCELTFullband20ms|EncoderCarriedDREDPayloadMatchesLibopusCELTFullbandLongFrames|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msCBR|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband40ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband60ms|EncoderCarriedDREDPayloadMatchesLibopusSilkWidebandLongFrames|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20ms|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40ms|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msStereo|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msStereoPayloadOnly|EncoderCarriedDREDPayloadMatchesLibopusHybridFullband40msStereo|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msStereo|EncoderCarriedDREDPayloadMatchesLibopusSilkWideband40msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusSilkWideband20msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusCELTFullband20msStereo|MultistreamEncoderCarriedDREDPayloadMatchesLibopusHybridFullband20msStereo)' -count=1
	run_parity -tags gopus_extra_controls . -run 'Test(DecoderExplicitDREDFirstConcealFrameBootstraps48kRuntime|DecoderExplicitDREDThreeConcealFramesBootstraps48kRuntime|DecoderExplicitDREDThreeConcealFramesManualStep48kRuntime|DecoderExplicitDREDThreeConcealFramesMixedHelpers48kRuntime)' -count=1
	run_parity -tags gopus_extra_controls . -run "$dred_stereo_recovery_root" -count=1
	run_parity -tags gopus_extra_controls . -run "$extra_controls_parity_silk_dred_root" -count=1
	run_parity -tags gopus_extra_controls . -run "$extra_controls_parity_decoder_root" -count=1
	require_no_skips "extra-controls parity"
}

usage() {
	echo "usage: $0 {dnn-blob-parity|core-oracles-parity|dred-tag|qext-parity|extra-controls-tag|extra-controls-parity}"
}

case "${1:-}" in
	dnn-blob-parity)
		gate_dnn_blob_parity
		;;
	core-oracles-parity)
		gate_core_oracles_parity
		;;
	dred-tag)
		gate_dred_tag
		;;
	qext-parity)
		gate_qext_parity
		;;
	extra-controls-tag)
		gate_extra_controls_tag
		;;
	extra-controls-parity)
		gate_extra_controls_parity
		;;
	*)
		usage
		exit 2
		;;
esac
